# Generated by Django 4.2.7 on 2023-11-09 22:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=40)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(default=datetime.datetime(2023, 11, 9, 22, 14, 4, 344663, tzinfo=datetime.timezone.utc))),
                ('published_at', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
