# Generated by Django 4.2.7 on 2023-11-09 22:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 9, 22, 32, 15, 805246, tzinfo=datetime.timezone.utc)),
        ),
    ]
